### ISSUE TITLE
React adoption checklist

### ISSUE THREAD

**Issue by ExpHP** [ExpHP/thpages#3]
Here I keep a list of things I need to come back to during the React refactor.

* [x] Make tips work again.
* [x] Use refractor to highlight
* [x] Replace `globalNames` with React state.
* [x] Completely exorcise `data-name`, `data-link`, `NameResolver` and `LinkResolver`.
* [x] Think about `data-tip`.  Maybe we still need this?
* [x] Convert markdown extensions to components
* [x] Do we need to be more careful with reading `window.location.hash`?
* [x] delete `postprocessConvertedMarkdown`
* [x] Fix the copypasta at the bottom of the various tables.js
* [x] table-footnotes
* [x] ~~look at [`remark-footnotes`](https://github.com/remarkjs/remark-footnotes)~~ who cares
* [x] fix all tipshow/tiphide
* [x] render links
* [x] change all anchored headings to use `{#id}`
* [x] make sure there's no automatic header ids (probably an option somewhere)
* [x] why does the ins table have borders
* [x] Disabling of nested tooltips inside tooltip bodies needs to be reimplemented as a remark plugin (part of the `:::is-tip` logic)
* [x] fix highlighting of current page in navbar **again**
* [ ] perform a check at runtime for any bad directives
     ```
     // find a custom element beginning with "exp-"
     let result = document.evaluate( "//*[starts-with(name(),'exp-')]", document, null, XPathResult.ANY_TYPE, null ).iterateNext();
     ```
* [x] ~~change `preventOverzealousTextDirectives` into a plugin that operates only on text nodes~~  changed the syntax to `:ref{r=...}` instead
* [x] how to reset scroll on new page?
* [x] scrolling to anchor
* [x] `<div class="gear">`
* [x] stats
* [ ] layer viewer
* [x] `couldn't parse ref :ref{r=anm:resampleMode tip=0}`
* [x] 404 on bad page
* [ ] "See the table entry for more details" was lost from tips

Things from the second rewrite:
* [x] Update the other tables besides STD
* [x] toolips are weirdly positioned due to async content...
* [x] settings page
* [x] markdown pages
* [x] truth maps
* [x] redirect to new HashRouter urls
* [ ] fix old links in MD not using HashRouter urls
* [x] "Show more" has the wrong cursor again
* [x] HTML in MD not working

Things to double check at the end:
* [ ] Check appearance of everything:
  * [x] `headless-table`
  * [x] `table-footnotes`
  * [x] `title`
  * [x] `c`
  * [x] ref in inline-code: see resampleMode
  * [x] tip with newlines in body: see `furiTip`
  * [x] stats table
  * [x] 404 on bad page
  * [x] more...
  * [x] embedded video
* [x] scroll positions:
  * [x] follow link to instruction
  * [ ] ~~follow link to instruction, hit back button (should go back to original scroll)~~  (this was already broken)
  * [ ] ~~with an anchor in the current url, scroll away from anchor, go to another page and hit back (should not return to anchor)~~  (this was already broken)
  * [ ] ~~with an anchor in current url, scroll away from anchor, and hit refresh (should not return to anchor)~~   (this was already broken)
  * [x] scroll down, navigate to other page:  should reset scroll to top
  * [x] follow a link to an instruction in the same table but another game (e.g. randMode)
